# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
        -   id: fmt
        -   id: clippy
-   repo: local
    hooks:
        - id: test
          name: cargo test
          description: Run tests with cargo test.
          entry: cargo test --
          language: rust
          types: [rust]
          stages: [push]
          args: []
